- name: Flutter | SDK | Set default version path
  ansible.builtin.set_fact:
    flutter_version_path: "{{ flutter_sdk_path }}/{{ flutter.sdk.default }}"


- name: Flutter | SDK | Lookup version directory
  ansible.builtin.stat:
    path:  "{{ flutter_version_path }}"
  register: flutter_version_dir


- name: Flutter | SDK | Fail on version directory not existing
  ansible.builtin.fail:
    msg: "Directory for default version {{ flutter.sdk.default }} was not found!"
  when: not flutter_version_dir.stat.exists


- name: Flutter | SDK | Set default directory
  ansible.builtin.set_fact:
    flutter_default_path: "{{ flutter_sdk_path }}/default"


- name: Flutter | SDK | Lookup default directory
  ansible.builtin.stat:
    path:  "{{ flutter_default_path }}"
  register: flutter_default_dir


- name: Flutter | SDK | Create default directory
  ansible.builtin.file:
    path: "{{ flutter_default_path }}"
    state: directory
    modification_time: preserve
    access_time: preserve
    owner: "root"
    group: "root"
    mode: 0755
  when:
    - not flutter_default_dir.stat.exists


- name: Flutter | SDK | Link default version
  ansible.builtin.file:
    src: "{{ flutter_version_path }}/bin/flutter"
    dest: "/usr/bin/flutter"
    force: true
    state: link
    modification_time: preserve
    access_time: preserve
    owner: "root"
    group: "root"
    mode: 0755
