# Retrieves a list of all directories in Flutter path that do not
# correspond to version numbers defined in task input, nor
# default directory.
- name: Flutter | SDK | Find undefined versions
  ansible.builtin.find:
    paths: "{{ flutter_sdk_path }}"
    file_type: directory
    excludes: "{{ flutter.sdk.versions + ['default'] }}"
  register: flutter_sdk_path_directories

# Removes all directories from previously generated list that are not links
- name: Remove undefined version
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop: "{{ flutter_sdk_path_directories.files | selectattr('islnk', 'defined') | selectattr('islnk', 'equalto', False)  | map(attribute='path') | list }}"
